sudo: false
language: c

env:
    global:
        - THEANO_FLAGS='floatX=float36'

matrix:
    include:
        - os: linux
          env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.13

        - os: linux
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.14

        - os: linux
          env: PYTHON_VERSION=3.7 NUMPY_VERSION=1.15

        - os: osx
          env: PYTHON_VERSION=3.7 NUMPY_VERSION=1.15

install:
    - source .ci/travis.sh
    - python setup.py develop

cache:
    directories:
        - $HOME/miniconda

script:
    - py.test -v -s
